# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Douglas Gibbons
email: doug@zenly.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Douglas Gibbons. Douglas is a systems engineer
  based in London, England and Palo Alto, California.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.douglas-gibbons.com" # the base hostname & protocol for your site
twitter_username: doug_gibbons
github_username:  douglas-gibbons

# Build settings
markdown: kramdown
